# Generated by Django 3.2 on 2021-11-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='pointsPossible',
            field=models.FloatField(default=0),
        ),
    ]
