# Generated by Django 3.2 on 2021-11-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211124_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dash',
        ),
    ]
