# Generated by Django 3.2 on 2021-11-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='onDashboard',
            field=models.BooleanField(default=False),
        ),
    ]
