# Generated by Django 3.2 on 2021-11-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_submission_ondashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='AAAAAAAA', max_length=8),
        ),
    ]
