# Generated by Django 3.2 on 2021-11-29 00:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default=api.models.generateCourseCode, max_length=8, unique=True),
        ),
    ]
